### ISSUE TITLE
Unable to find library brolib_x64.dll (version 2.0.2)

### ISSUE THREAD

**Issue by MarcinZiabek** [XieJJ99/brotli.net#16]
When using the newest version of the library (2.0.2), my NUnit tests (.NET framework 4.7.1) stopped working. Below you can find the exact message:

```
System.TypeInitializationException : The type initializer for 'Brotli.Brolib64' threw an exception.
  ----> System.TypeInitializationException : The type initializer for 'Brotli.LibPathBootStrapper' threw an exception.
  ----> System.NotSupportedException : Unable to find library brolib_x64.dll
   at Brotli.Brolib.BrotliEncoderCreateInstance()
   at Brotli.BrotliStream..ctor(Stream baseStream, CompressionMode mode, Boolean leaveOpen)
   at SpatialCommon.AlignmentBinaryFormat.Helpers.DataCompressor.Compress(Byte[] data)
   at SpatialCommon.Tests.AlignmentBinaryFormat.Helpers.DataCompressorTests.Compress() in PATH_TO_FILE.cs:line 21
--TypeInitializationException
   at Brotli.LibPathBootStrapper.get_LibPath()
   at Brotli.Brolib64..cctor()
--NotSupportedException
   at Brotli.LibPathBootStrapper..cctor()
```

**Reason: native dlls are not coppied into bin\Debug folder. When I copy them by hand, tests work once again.**

**Comment by XieJJ99** [comment]
@MarcinZiabek Thanks for the feedback, I'll verify this on .NET FX 4.7.1 later.

**Comment by XieJJ99** [comment]
@MarcinZiabek The issue is fixed is v2.0.3, also the .NET FX UT is added. Besides .NET Standard 2, now the new version support .NET Framework v4.5 and above, could you update the package and verify the issue is resolved?

**Comment by MarcinZiabek** [comment]
@XieJJ99 I updated the package to version 2.0.3. Unfortunately, the issue is not resolved. I prepared the simplest solution that can be used for problem analysis, please take a look here: https://github.com/MarcinZiabek/brotli.net-unable-to-find-library-issue

When .NET Framework 4.7.1 is used, the exception is thrown. When you copy the same code to .NET Core project, everything works fine.

Once again, the problem comes from native dlls not being copied into bin\Debug folder. When I copy brolib_x64.dll and brolib_x86.dll into bin\Debug, the test works fine.

**Comment by XieJJ99** [comment]
@MarcinZiabek Thanks for the information. Now I have updated the .targets so that  all the runtime dlls  will copy to the output directory. You could update the package to 2.0.3.1 .
I have tested your projects with the package and it seems OK.
Please ping me if the issue still exists on your environment.

**Comment by MarcinZiabek** [comment]
@XieJJ99 I have made a test against my example project and, unfortunately, I am still encountering the problem. Can you please test it once again?

I see some progress there. The folder runtimes/win/native with dlls is copied into bin\Debug. However, in my case, Brotli.Net is looking for a file bin/Debug/brolib_x64.dll instead of bin/Debug/runtimes/win/native/brolib_x64.dll. So still, it cannot find it...

Every time you are testing, please make sure that the folder bin/Debug is deleted before making a test. Otherwise, dlls maybe cached... If you need any more information, please feel free to ask ;)

**Comment by XieJJ99** [comment]
@MarcinZiabek Thanks for the help and the patience.
After some investigation, I found this is not a issue with path, it's a issue that NUnit didn't run the test under the Debug directory so it could not recognize the relative path runtimes/win/native.
After I added the absolute path to search directory, the issue is resolved, your test project runs successfully.
Please update the package to **v2.0.3.2** or **v2.0.4**. If you could not find the package from nuget at this moment, you could build it from source and installed from local.
Please ping me if the issue still occurs.

**Comment by MarcinZiabek** [comment]
@XieJJ99 At this point I can confirm that the new version 2.0.4 is working as expected. Thank you very much for your excellent support!

**Comment by Brain2000** [comment]
It looks like version 2.1.1 still has a variant of this issue.
This just happened to me using this library in production for the first time. We have temporarily rolled it out until we can find out why.

            "Message": "An error has occurred.",
            "ExceptionMessage": "The type initializer for 'Brotli.LibPathBootStrapper' threw an exception.",
            "ExceptionType": "System.TypeInitializationException",
            "StackTrace": "   at Brotli.LibPathBootStrapper.get_LibPath()\r\n   at Brotli.Brolib64..cctor()",
            "InnerException": {
                "Message": "An error has occurred.",
                "ExceptionMessage": "Unable to find library brolib_x64.dll",
                "ExceptionType": "System.NotSupportedException",
                "StackTrace": "   at Brotli.LibPathBootStrapper..cctor()"
            }

It appears that the LibPath property may not be working properly. Here is our folder structure:

```
C:\inetpub\newui\webservices\rest\bin\   <-- root folder with our webapi application
                   Brotli.Core.dll
                   runtimes\
                          win\
                         native\
                                 brolib_x64.dll

```

**Comment by Brain2000** [comment]
I cannot seem to find how this could have possibly happened, but it kept failing intermittently after restarting the process multiple times.

This is a high traffic site with a lot of constant simultaneous calls, and perhaps something is causing an issue in NativeLibraryLoader.cs where it cannot find the assembly paths in the function GetPossibleRuntimeDirectories() !?

It tries to resolve the library path from within a static constructor so it only runs once, but if it throws the exception, it will continue to fail and the application will need to be restarted in order to try again.

I ran the code manually to make sure the paths retrieved from GetPossibleRuntimeDirectories() looked correct, and it does. I'm curious as to what path values are retrieved when it fails, but I can't put this back into production to find out.

By the way, this never fails in our test environment. It seems to happen when the w3wp.exe process is starting and a lot of requests are in the queue waiting.

**Comment by Brain2000** [comment]
It looks like some of the paths are sometimes coming back as this value:

`
C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Temporary ASP.NET Files\rest\44050a20\501bf9d7\assembly\dl3\afbe12f7\41d11971_f3e3d801\runtimes\win\native
`
